# Generated by Django 4.0.5 on 2022-06-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_avatar_profileimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileImage',
            new_name='Profile',
        ),
    ]
