# Generated by Django 4.0.5 on 2022-06-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
